### ISSUE TITLE
Issue: Prettier config file missing

### ISSUE THREAD

**Issue by FireeagSaini** [gurpreet-legend/Alan-Feed#17]
### What is the issue?

Nowadays everyone uses [Prettier](https://prettier.io/), An automated code formatting tool.

The issue is everyone have different **global settings** of prettier according to their style. BUT this can **cause useless changes** to opensource projects as many people works on same code.

So having a `prettier config file` inside project directory can resolve this issue.

### How to solve this issue?

adding a file `.prettierrc` and `.prettierignore` will solve this issue

**Comment by FireeagSaini** [comment]
close by merging #18  PR.

**Comment by gurpreet-legend** [comment]
@FireeagSaini , this issue has already been assigned to someone else, it's open at issue #5

**Comment by gurpreet-legend** [comment]
You can try solving some other open issues

**Comment by FireeagSaini** [comment]
did he/she resolved it?
